apiVersion: tailscale.com/v1alpha1
kind: Connector
metadata:
  name: subnet-router
  namespace: tailscale
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  subnetRouter:
    advertiseRoutes:
      - "10.10.0.0/24"
  tags:
    - "tag:k8s"
